stateDiagram
  current_player: oracle
  make_move: transition

  [*] --> current_player
  current_player --> active_player
  current_player --> passive_player
  active_player --> make_move
  make_move --> current_player
  passive_player --> current_player
  passive_player --> make_move: Dependant
  make_move --> [*]
  passive_player --> [*]
